//
//  MapInteractor.swift
//  StudiousBus
//
//  Created by vinicius.custodio on 11/05/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapBusinessLogic {
    func retrieveStations(_ request: Map.RetrieveStations.Request)
}

protocol MapDataStore {
    //var name: String { get set }
}

class MapInteractor: MapBusinessLogic, MapDataStore {
    var presenter: MapPresentationLogic?
    var worker: MapWorker = MapWorker()

    var currentDataTask: URLSessionDataTask?

    func retrieveStations(_ request: Map.RetrieveStations.Request) {
        currentDataTask?.cancel()

        self.currentDataTask = worker.retrieveStations(in: request.currentLocation) { (result) in
            switch result {
            case .success(let stationsResponse):
                let response = Map.RetrieveStations.Response(stations: stationsResponse.stations)
                self.presenter?.presentStations(response: response)
            case .failure(let error):
                print("a")
            }
        }
    }
}
