//
//  MapModels.swift
//  StudiousBus
//
//  Created by vinicius.custodio on 11/05/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLocation

enum Map {
    enum RetrieveStations {
        struct Request {
            let currentLocation: CLLocationCoordinate2D
        }

        struct Response {
            let stations: [Station]
        }

        struct ViewModel {
            let stations: [StationViewModel]

            struct StationViewModel {
                let name: String
                let type: String
                let id: String
                let location: CLLocationCoordinate2D
            }
        }
    }
}
