//
//  MapPresenter.swift
//  StudiousBus
//
//  Created by vinicius.custodio on 11/05/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapPresentationLogic {
    func presentStations(response: Map.RetrieveStations.Response)
}

class MapPresenter: MapPresentationLogic {
    weak var viewController: MapDisplayLogic?
    
    // MARK: Do something
    func presentStations(response: Map.RetrieveStations.Response) {
        let stationsViewModel = response.stations.map { (station) -> Map.RetrieveStations.ViewModel.StationViewModel in
            Map.RetrieveStations.ViewModel.StationViewModel(name: station.place.name,
                                                            type: station.place.type,
                                                            id: station.place.id,
                                                            location: station.place.location.to2DCoordinate)
        }
        
        let viewModel = Map.RetrieveStations.ViewModel(stations: stationsViewModel)
        viewController?.displayStations(viewModel: viewModel)
    }
}
