//
//  MapWorker.swift
//  StudiousBus
//
//  Created by vinicius.custodio on 11/05/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLocation

class MapWorker {

    let hereService = HereService()

    func retrieveStations(in location: CLLocationCoordinate2D, completion: @escaping (Result<StationsResponse, Error>) -> Void) -> URLSessionDataTask {
        let request = StationsRequest(location: location)
        return hereService.send(apiRequest: request, callback: completion)
    }
}
