# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StudiousTrain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StudiousTrain
  pod 'URLQueryItemEncoder'

  target 'StudiousTrainTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StudiousTrainUITests' do
    # Pods for testing
  end

end
